name: CI/CD to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "gema" ]; then
              git clone git@github.com:gemm123/go-cicd-project.git gema
            fi
            cd gema
            git pull origin main
            docker build -t go-cicd-project .
            docker stop go-cicd-project || true
            docker rm go-cicd-project || true
            docker run -d -p 8080:8080 --name go-cicd-project go-cicd-project